=== tinatomova/Semantic-Web/project/Wines.dtd
<!ELEMENT Catalog (Wineries, Regions, Wine*)>
<!ELEMENT Wineries (Winery*)>
<!ELEMENT Winery EMPTY>
<!ATTLIST Winery 
        id ID #REQUIRED 
        name CDATA #REQUIRED>
<!ELEMENT Regions (Region*)>
<!ELEMENT Region EMPTY>
<!ATTLIST Region
        id ID #REQUIRED 
        name CDATA #REQUIRED>
<!ELEMENT Wine (image?, GeneralInfo, TypeInfo, Price, Alcohol, Rating, AdditionalInfo)>
<!ATTLIST Wine 
        id ID #REQUIRED 
        winery IDREF #REQUIRED>
<!ELEMENT image EMPTY>
<!ATTLIST image href ENTITY #REQUIRED>
<!NOTATION png PUBLIC "images/png">
<!ELEMENT GeneralInfo (Name, Origin)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Origin (Country, Area, Terroir)>
<!ATTLIST Origin
        region IDREF #REQUIRED>
<!ELEMENT Country (#PCDATA)>
<!ELEMENT Area (#PCDATA)>
<!ELEMENT Terroir (#PCDATA)>
<!ELEMENT TypeInfo (Type, Color, Year, Package)>
<!ELEMENT Type (#PCDATA)>
<!ELEMENT Color (#PCDATA)>
<!ELEMENT Year (#PCDATA)>
<!ELEMENT Package (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT Alcohol (#PCDATA)>
<!ELEMENT Rating (#PCDATA)>
<!ELEMENT AdditionalInfo (SommelierDescription, ConsumeWith, About)>
<!ELEMENT SommelierDescription (Aroma, Body, Aftertaste)>
<!ELEMENT Aroma (#PCDATA)>
<!ELEMENT Body (#PCDATA)>
<!ELEMENT Aftertaste (#PCDATA)>
<!ELEMENT ConsumeWith (#PCDATA)>
<!ELEMENT About (#PCDATA)>

=== tinatomova/Semantic-Web/project/Wines.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Wines.xsl"?>
<!DOCTYPE Catalog SYSTEM "Wines.dtd"[
<!ENTITY wine1 SYSTEM "images/MediValleyVelvetTouch.jpg" NDATA png>
<!ENTITY wine2 SYSTEM "images/MidalidareGoldBrut.jpg" NDATA png>
<!ENTITY wine3 SYSTEM "images/RedChurchSelectionIndividuelle.jpg" NDATA png>
<!ENTITY wine4 SYSTEM "images/DragomirDessertWine.jpg" NDATA png>
<!ENTITY wine5 SYSTEM "images/LogodajMelnikPrime.jpg" NDATA png>
<!ENTITY wine6 SYSTEM "images/DragomirRoseCepage.jpg" NDATA png>
<!ENTITY wine7 SYSTEM "images/ChateauCopsaLV.png" NDATA png>
<!ENTITY wine8 SYSTEM "images/FourFriendsBlackShadow.jpg" NDATA png>
]>
<Catalog>
    <Wineries>
        <Winery name="Меди Вали" id="a"/>
        <Winery name="Мидалидаре Естейт" id="b"/>
        <Winery name="Ред Чърч Естейт" id="c"/>
        <Winery name="Драгомир Естейт" id="d"/>
        <Winery name="Логодаш" id="e"/>
        <Winery name="Шато Копса" id="f"/>
        <Winery name="Винарна Four Friends" id="g"/>
    </Wineries>
    <Regions>
        <Region name="Дунавска равнина" id="r1"/>
        <Region name="Черноморски" id="r2"/>
        <Region name="Розова долина" id="r3"/>
        <Region name="Тракийска низина" id="r4"/>
        <Region name="Долината на Струма" id="r5"/>
    </Regions>
    <Wine winery="a" id="a1">
        <image href="images/MediValleyVelvetTouch.png"/>
        <GeneralInfo>
            <Name>Medi Valley Velvet Touch</Name>
            <Origin region="r1">
                <Country>България</Country>
                <Area>с. Градец</Area>
                <Terroir>Климатът е умерено-континентален с влияние от река Дунав. Лозето се намира на 125 м надморска
                    височина върху терен с подчертана денивелация. Почвата е хумуснокарбонатна, образувана върху основна скала варовик. Премесена е с пясък и глина, а безброй черупки от миди и ракообразни с древен произход я правят уникална.</Terroir>
            </Origin>           
        </GeneralInfo>
        <TypeInfo>
            <Type>Каберне фран</Type>
            <Color>Червенo вино</Color>
            <Year>2021</Year>
            <Package>750ml</Package>
        </TypeInfo>
        <Price>29,99 лв.</Price>
        <Alcohol>14,5%</Alcohol>
        <Rating>4/5</Rating>
        <AdditionalInfo>
            <SommelierDescription>
                <Aroma>Ароматът е изграден от ухания на касис, зрял плод, листа и плодове на боровинка, допълнени от шоколад, ванилия и конфи тонове</Aroma>
                <Body>Тялото е обемно, пикантно, агресивно плодово, но много меко.</Body>
                <Aftertaste>Дълъг и приятен послевкус.</Aftertaste>
            </SommelierDescription>
            <ConsumeWith>Пасва си с почти всички сирена като горгонзола, пармезан, швейцарски твърди сирена, чедър, козе сирене, сини сирена. Също и с гриловани меса – свинско, телешко патешко, агнешко.</ConsumeWith>
            <About>Избрахме добре узряло, ръчно брано и доставено във винарната грозде в касетки. Селектирахме Каберне франа на двойна сортировъчна маса. Ферментацията е в инокс при температури 25-30°С. Виното отлежа 10 месеца във френски дъбови бъчви тип „барик”, за да постигне завършеност и хармония. Успяхме да изпълним целта си – да покажем атрактивността на сорта и специфичността тероара.</About>
        </AdditionalInfo>
    </Wine>

    <Wine winery="b" id="b1">
        <image href="images/MidalidareGoldBrut.png"/>
        <GeneralInfo>
            <Name>Midalidare Sparkling Gold Brut</Name>
            <Origin region="r4">
                <Country>България</Country>
                <Area>Източна Тракийска Низина, Могилово</Area>
                <Terroir>Засадени са на северни склонове – местата са специално подбрани с оглед ограничаване количеството слънчева светлина. Насажденията са на средна надморска височина 360-390 метра при 10% наклон. Почвите са с високо съдържание на варовик. Температурните амплитуди са големи, но надморската височина предотвратява измръзването на лозите от пролетни слани. Уникалният микроклимат в района на Могилово се характеризира с мека зима, топло лято и оптимално съотношение между слънцегреене и валежи. </Terroir>
            </Origin>           
        </GeneralInfo>
        <TypeInfo>
            <Type>Шардоне</Type>
            <Color>Бяло вино</Color>
            <Year>2020</Year>
            <Package>750ml</Package>
        </TypeInfo>
        <Price>59.90 лв.</Price>
        <Alcohol>12%</Alcohol>
        <Rating>5/5</Rating>
        <AdditionalInfo>
            <SommelierDescription>
                <Aroma>Искрящ, златисто–жълт цвят. Плътен мус от фини перли с много продължителна игра. Интензивният плодов аромат на зрели ябълки, круши и зелени билки прелива в прекрасно балансиран и освежаващ вкус.</Aroma>
                <Body>Мидалидаре Спарклинг Голд е вино със стегнато тяло, добра структура и изключителен потенциал за отлежаване.</Body>
                <Aftertaste></Aftertaste>
            </SommelierDescription>
            <ConsumeWith>Прекрасно се съчетава с пържени храни, ракообразни, мазни риби, бели меса, паста, твърди сирена и десерти. Изключително добре се комбинира с треска, маринована в бира, с гарнитура от лучени кръгчета; пушена сьомга с хрупкави картофи, пилешки пирог, поръсен с натрошени бисквити; кебапи Тандури.</ConsumeWith>
            <About>Средната възраст на лозята е 7 години. Беритбата се провежда в началото на август. Гроздовете се пресоват цели по стъпална програма и се разделят на фракции. Следва избистряне на мъстта, декантиране и ферментация при контролирана температура. Виното отлежава върху фините утайки в продължение на няколко месеца, след което се блендира и подлага на студена стабилизация. Следва стерилна филтрация и засяване с активни винени дрожди за вторична ферментация: няколко часа след засяването с дрожди виното се бутилира и се затваря с кроненкоркови тапи. Ферментацията продължава около 40 дни. След нея виното отлежава върху дрождената утайка най-малко 48 месеца, след което се подлага на ремюаж. Следва дегоржаж при контролирана температура. Добавя се експедиционен ликьор и се поставя коркова тапа и кошница. Следва внимателно разклащане на бутилките, за да се хомогенизира виното, както и финална проверка на бистротата му. Процесът приключва с минимум 3-месечно отлежаване в бутилка.</About>
        </AdditionalInfo>
    </Wine>

    <Wine winery="c" id="c1">
        <image href="images/RedChurchSelectionIndividuelle.png"/>
        <GeneralInfo>
            <Name>Red Church Selection Individuelle</Name>
            <Origin region="r4">
                <Country>България</Country>
                <Area>Полите на Родопите, Перущица</Area>
                <Terroir>Структурата на почвата е пясъчливо-глинесто-камениста с естествен наклон от 5-9%,допринасящ за естествено дрениране на водните потоци.Така ,поставена в трудни условия,лозата е прдизвикана да даде най-доброто от себе си,изразявайки особеностите на тероарът и неговият потенциал.Характерно за микроклимата са леките въздушни потоци които влиаят благоприятно за формирането на финните аромати в гроздето,както и естественото проветряване на листната маса. </Terroir>
            </Origin>           
        </GeneralInfo>
        <TypeInfo>
            <Type>каберне совиньон 55%, мерло 35 %, каберне фран 10%</Type>
            <Color>Червенo вино</Color>
            <Year>2018</Year>
            <Package>750ml</Package>
        </TypeInfo>
        <Price>74.00 лв.</Price>
        <Alcohol>14,5%</Alcohol>
        <Rating>5/5 №1 Divino TOP 50</Rating>
        <AdditionalInfo>
            <SommelierDescription>
                <Aroma>Перфектен баланс между зрял, но сложен, ароматен плод с добра изразена свежест и разгръщащи се, копринени и заоблени танини. Тъмният и наситен цвят е последван от мощна атака с нотки на напълно узрели червени тъмни плодове и пикантни, балсамови и какаови нотки.</Aroma>
                <Body>В устата става изразителен и богат, с голяма плътност и обемни и идеално меки танини. </Body>
                <Aftertaste>Плодовите нотки са подчертани от добре интегрираният дъб - завършващ в свеж и жив завършек с ясно изразени нотки на какао.</Aftertaste>
            </SommelierDescription>
            <ConsumeWith>Комбинира се добре с телешко, агнешко и дивеч</ConsumeWith>
            <About>Виното е съзрявало в нови френскли барици за период от 12 месеца. Самите грижи за лозята са много специални и всички те се извършват ръчно,като се отнасяме специфично и грижливо спрямо особеностите на всеки един сорт,парцел,на фона на стилът на вино,който искаме да сътворим в лозята и да го трансформираме в избата.  Абсолютно безкомпромисно подхождаме по отношение на бутилките ни, които са френски и италиански. Коркът, който купуваме е от Португалия.Името на винарската ни изба: Лозовите ни масиви гледат Червената църква, която е доказано най-старата църква на Балканския полуостров. </About>
        </AdditionalInfo>
    </Wine>

    <Wine winery="d" id="d1">
        <image href="images/DragomirDessertWine.png"/>
        <GeneralInfo>
            <Name>Dragomir Dessert Wine</Name>
            <Origin region="r4">
                <Country>България</Country>
                <Area>с. Димитровче</Area>
                <Terroir>Районът на Димитровче се очертава като един от най-топлите в България, характеризиращ се със сухо и горещо лято и топла и дъждовна зима. </Terroir>
            </Origin>           
        </GeneralInfo>
        <TypeInfo>
            <Type>Димят</Type>
            <Color>Оранжево десертно вино</Color>
            <Year>2012</Year>
            <Package>500ml</Package>
        </TypeInfo>
        <Price>49.90 лв.</Price>
        <Alcohol>16.0%</Alcohol>
        <Rating>3/5</Rating>
        <AdditionalInfo>
            <SommelierDescription>
